os: linux
dist: bionic
language: node_js
node_js:
    - node
before_install:
    - pip install --user codecov
after_success:
    - codecov --file coverage/lcov.info --disable search

- name: NPM Target
  uses: anna-money/github-actions-npm@v4
